// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'home',
    'log-in',
    {
      type: 'category',
      label: 'The Backend',
      items: [        
        'the-backend/dashboard',
        {
          type: 'category',
          label: 'Backend Menu',
          items: [
            'the-backend/menu/dashboard-menu',
            'the-backend/menu/analytics',
            'the-backend/dashboard',
            'the-backend/menu/pages',
            'the-backend/menu/fitness',
            'the-backend/menu/workouts',
            'the-backend/menu/exercises',
            'the-backend/menu/gyms',
            'the-backend/menu/routes',
            'the-backend/menu/posts',
            'the-backend/menu/resources',
            'the-backend/menu/links',
            'the-backend/menu/books',
            'the-backend/menu/podcasts',
            'the-backend/menu/organisation',
            'the-backend/menu/organisations',
            'the-backend/menu/people',
            'the-backend/menu/staff-networks',
            'the-backend/menu/media',
            'the-backend/menu/recipes',
            'the-backend/menu/days-out',
            'the-backend/menu/discount-codes',
            'the-backend/menu/groups',
            'the-backend/menu/events',
            'the-backend/menu/ivory-search',
            'the-backend/menu/wpforms',
            'the-backend/menu/appearance',
            'the-backend/menu/themes',
            'the-backend/menu/patterns',
            'the-backend/menu/customize',
            'the-backend/menu/menus',
            'the-backend/menu/plugins',
            'the-backend/menu/users',
            'the-backend/menu/tools',
            'the-backend/menu/settings',
            'the-backend/menu/secure-custom-fields',
            'the-backend/menu/ourspace-platform-settings',
            'the-backend/menu/ourspace-settings',
            'the-backend/menu/disclaimer-banner',
            'the-backend/menu/wp-mail-smtp',
            'the-backend/menu/yoast-seo',
            'the-backend/menu/wp-optimize',
            'the-backend/menu/smush',
            'the-backend/menu/page-exclusions'
          ]
        },
                {
          type: 'category',
          label: 'Topic Management',
          items: [
            'topics/what-is-a-topic',
            'topics/creating-topic',
            'topics/creating-child-topic'
          ]
        },
        {
          type: 'category',
          label: 'Content Management',
          items: [
            {
              type: 'category',
              label: 'Fitness',
              items: [
                'the-backend/content-management/workouts',
                'the-backend/content-management/exercises',
                'the-backend/content-management/gyms',
                'the-backend/content-management/routes',
              ]
            },
            {
              type: 'category',
              label: 'Resources',
              items: [
                'the-backend/content-management/links',
                'the-backend/content-management/books',
                'the-backend/content-management/podcasts',
              ]
            },
            {
              type: 'category',
              label: 'Organisation',
              items: [
                'the-backend/content-management/organisations',
                'the-backend/content-management/people',
                'the-backend/content-management/staff-networks',
              ]
            },
            'the-backend/content-management/recipes',
            'the-backend/content-management/days-out',
            'the-backend/content-management/discount-codes',
            'the-backend/content-management/groups',
            'the-backend/content-management/events',
          ]
        },
        'the-backend/navigation-management',
        {
          type: 'category',
          label: 'User Management',
          items: [
            'the-backend/user-management/adding-new-users',
            'the-backend/user-management/roles'
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [        
        'development/development',
        'development/how-to-clone',
        'development/linting',
        'development/release-workflow'
      ],
    },
  ],

};

export default sidebars;
