// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'home',
    'log-in',
    {
      type: 'category',
      label: 'Topic Management',
      items: [
        'topics/what-is-a-topic',
        'topics/creating-topic',
        'topics/creating-child-topic'
      ]
    },
    {
      type: 'category',
      label: 'Content Management',
      items: [
        {
          type: 'category',
          label: 'Fitness',
          items: [
            'content-management/workouts',
            'content-management/exercises',
            'content-management/gyms',
            'content-management/routes',
          ]
        },
        {
          type: 'category',
          label: 'Resources',
          items: [
            'content-management/links',
            'content-management/books',
            'content-management/podcasts',
          ]
        },
        {
          type: 'category',
          label: 'Organisation',
          items: [
            'content-management/organisations',
            'content-management/people',
            'content-management/staff-networks',
          ]
        },
        'content-management/recipes',
        'content-management/days-out',
        'content-management/discount-codes',
        'content-management/groups',
        'content-management/events',
      ]
    },
    {
      type: 'category',
      label: 'Administration',
      items: [        
        'administration/dashboard',
        {
          type: 'category',
          label: 'Menu Structure',
          items: [
            'administration/menu/dashboard-menu',
            'administration/menu/analytics',
            'administration/dashboard',
            'administration/menu/pages',
            'administration/menu/fitness',
            'administration/menu/workouts',
            'administration/menu/exercises',
            'administration/menu/gyms',
            'administration/menu/routes',
            'administration/menu/posts',
            'administration/menu/resources',
            'administration/menu/links',
            'administration/menu/books',
            'administration/menu/podcasts',
            'administration/menu/organisation',
            'administration/menu/organisations',
            'administration/menu/people',
            'administration/menu/staff-networks',
            'administration/menu/media',
            'administration/menu/recipes',
            'administration/menu/days-out',
            'administration/menu/discount-codes',
            'administration/menu/groups',
            'administration/menu/events',
            'administration/menu/ivory-search',
            'administration/menu/wpforms',
            'administration/menu/appearance',
            'administration/menu/themes',
            'administration/menu/patterns',
            'administration/menu/customize',
            'administration/menu/menus',
            'administration/menu/plugins',
            'administration/menu/users',
            'administration/menu/tools',
            'administration/menu/settings',
            'administration/menu/secure-custom-fields',
            'administration/menu/ourspace-platform-settings',
            'administration/menu/ourspace-settings',
            'administration/menu/disclaimer-banner',
            'administration/menu/wp-mail-smtp',
            'administration/menu/yoast-seo',
            'administration/menu/wp-optimize',
            'administration/menu/smush',
            'administration/menu/page-exclusions'
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [        
        'development/development',
        'development/how-to-clone',
        'development/linting',
        'development/release-workflow'
      ],
    },
  ],

};

export default sidebars;
